### ISSUE TITLE
Bump to latest WSL Preview

### ISSUE THREAD

**Issue by WSLUser** [Biswa96/wslg#2]
You mentioned you'd update when the next WSL Preview released. Well it did sometime last week and uses the latest WSLg version as far as I can tell so hoping you'll update now and resolve the conflict that I brought up before.

**Comment by Biswa96** [comment]
As promised, I have rebased Win10 branch in this repository. Also there are some changes in the command, see README file in [initrdg](https://github.com/Biswa96/initrdg) repository. Feel free to close the issue if things are working well.

I have a plan to add GitHub Actions in initrdg repository to build both wslgd and initrd.img files. That may make testing easier.

**Comment by Biswa96** [comment]
Feel free to close this issue if fixed.
